// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: agent/api/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaunchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OCI image reference (e.g. "docker.io/library/nginx:latest").
	ImageRef string `protobuf:"bytes,1,opt,name=image_ref,json=imageRef,proto3" json:"image_ref,omitempty"`
	// Command to run inside the container. If empty, the image entrypoint is used.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// Environment variables passed to the container ("KEY=VALUE").
	Env           []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRequest) Reset() {
	*x = LaunchRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRequest) ProtoMessage() {}

func (x *LaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRequest.ProtoReflect.Descriptor instead.
func (*LaunchRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchRequest) GetImageRef() string {
	if x != nil {
		return x.ImageRef
	}
	return ""
}

func (x *LaunchRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *LaunchRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

type LaunchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Podman container ID.
	ContainerId string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// SHA-256 OCI manifest digest that was measured.
	ManifestDigest string `protobuf:"bytes,2,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	// Hex-encoded RTMR[2] value after extension (assumes zero initial state;
	// may not match actual RTMR[2] on cloud CVMs).
	Rtmr2Value string `protobuf:"bytes,3,opt,name=rtmr2_value,json=rtmr2Value,proto3" json:"rtmr2_value,omitempty"`
	// Hex-encoded workload measurement that was extended into RTMR[2].
	// This is pad48(SHA256(manifest_digest || "\0" || command...)).
	// A verifier can compute expected RTMR[2] as SHA384(rtmr2_pre || this).
	WorkloadMeasurement string `protobuf:"bytes,4,opt,name=workload_measurement,json=workloadMeasurement,proto3" json:"workload_measurement,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LaunchResponse) Reset() {
	*x = LaunchResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchResponse) ProtoMessage() {}

func (x *LaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchResponse.ProtoReflect.Descriptor instead.
func (*LaunchResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *LaunchResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LaunchResponse) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *LaunchResponse) GetRtmr2Value() string {
	if x != nil {
		return x.Rtmr2Value
	}
	return ""
}

func (x *LaunchResponse) GetWorkloadMeasurement() string {
	if x != nil {
		return x.WorkloadMeasurement
	}
	return ""
}

type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-supplied report data, must be exactly 64 bytes.
	ReportData    []byte `protobuf:"bytes,1,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteRequest) GetReportData() []byte {
	if x != nil {
		return x.ReportData
	}
	return nil
}

type QuoteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw TDX quote blob.
	Quote []byte `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	// PEM-encoded certificate chain for quote signature verification.
	CertChain     []byte `protobuf:"bytes,2,opt,name=cert_chain,json=certChain,proto3" json:"cert_chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *QuoteResponse) GetQuote() []byte {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *QuoteResponse) GetCertChain() []byte {
	if x != nil {
		return x.CertChain
	}
	return nil
}

type RATLSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RATLSRequest) Reset() {
	*x = RATLSRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RATLSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RATLSRequest) ProtoMessage() {}

func (x *RATLSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RATLSRequest.ProtoReflect.Descriptor instead.
func (*RATLSRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{4}
}

type RATLSResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM-encoded X.509 certificate containing the TDX quote.
	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	// PEM-encoded private key for the ephemeral TLS keypair.
	PrivateKey    []byte `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RATLSResponse) Reset() {
	*x = RATLSResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RATLSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RATLSResponse) ProtoMessage() {}

func (x *RATLSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RATLSResponse.ProtoReflect.Descriptor instead.
func (*RATLSResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *RATLSResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *RATLSResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{6}
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the agent is ready to accept requests.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Whether TDX hardware is detected and available.
	TdxAvailable bool `protobuf:"varint,2,opt,name=tdx_available,json=tdxAvailable,proto3" json:"tdx_available,omitempty"`
	// Human-readable status message.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_agent_api_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_api_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_api_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusResponse) GetTdxAvailable() bool {
	if x != nil {
		return x.TdxAvailable
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_api_v1_agent_proto protoreflect.FileDescriptor

const file_agent_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x18agent/api/v1/agent.proto\x12\x14attestation.agent.v1\"X\n" +
	"\rLaunchRequest\x12\x1b\n" +
	"\timage_ref\x18\x01 \x01(\tR\bimageRef\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\"\xb0\x01\n" +
	"\x0eLaunchResponse\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12'\n" +
	"\x0fmanifest_digest\x18\x02 \x01(\tR\x0emanifestDigest\x12\x1f\n" +
	"\vrtmr2_value\x18\x03 \x01(\tR\n" +
	"rtmr2Value\x121\n" +
	"\x14workload_measurement\x18\x04 \x01(\tR\x13workloadMeasurement\"/\n" +
	"\fQuoteRequest\x12\x1f\n" +
	"\vreport_data\x18\x01 \x01(\fR\n" +
	"reportData\"D\n" +
	"\rQuoteResponse\x12\x14\n" +
	"\x05quote\x18\x01 \x01(\fR\x05quote\x12\x1d\n" +
	"\n" +
	"cert_chain\x18\x02 \x01(\fR\tcertChain\"\x0e\n" +
	"\fRATLSRequest\"R\n" +
	"\rRATLSResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\fR\n" +
	"privateKey\"\x0f\n" +
	"\rStatusRequest\"e\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12#\n" +
	"\rtdx_available\x18\x02 \x01(\bR\ftdxAvailable\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xfd\x02\n" +
	"\x10AttestationAgent\x12\\\n" +
	"\x0fLaunchContainer\x12#.attestation.agent.v1.LaunchRequest\x1a$.attestation.agent.v1.LaunchResponse\x12S\n" +
	"\bGetQuote\x12\".attestation.agent.v1.QuoteRequest\x1a#.attestation.agent.v1.QuoteResponse\x12^\n" +
	"\x13GetRATLSCredentials\x12\".attestation.agent.v1.RATLSRequest\x1a#.attestation.agent.v1.RATLSResponse\x12V\n" +
	"\tGetStatus\x12#.attestation.agent.v1.StatusRequest\x1a$.attestation.agent.v1.StatusResponseB@Z>github.com/davidcao/attestation-two-stage/agent/api/v1;agentv1b\x06proto3"

var (
	file_agent_api_v1_agent_proto_rawDescOnce sync.Once
	file_agent_api_v1_agent_proto_rawDescData []byte
)

func file_agent_api_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_api_v1_agent_proto_rawDesc), len(file_agent_api_v1_agent_proto_rawDesc)))
	})
	return file_agent_api_v1_agent_proto_rawDescData
}

var file_agent_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agent_api_v1_agent_proto_goTypes = []any{
	(*LaunchRequest)(nil),  // 0: attestation.agent.v1.LaunchRequest
	(*LaunchResponse)(nil), // 1: attestation.agent.v1.LaunchResponse
	(*QuoteRequest)(nil),   // 2: attestation.agent.v1.QuoteRequest
	(*QuoteResponse)(nil),  // 3: attestation.agent.v1.QuoteResponse
	(*RATLSRequest)(nil),   // 4: attestation.agent.v1.RATLSRequest
	(*RATLSResponse)(nil),  // 5: attestation.agent.v1.RATLSResponse
	(*StatusRequest)(nil),  // 6: attestation.agent.v1.StatusRequest
	(*StatusResponse)(nil), // 7: attestation.agent.v1.StatusResponse
}
var file_agent_api_v1_agent_proto_depIdxs = []int32{
	0, // 0: attestation.agent.v1.AttestationAgent.LaunchContainer:input_type -> attestation.agent.v1.LaunchRequest
	2, // 1: attestation.agent.v1.AttestationAgent.GetQuote:input_type -> attestation.agent.v1.QuoteRequest
	4, // 2: attestation.agent.v1.AttestationAgent.GetRATLSCredentials:input_type -> attestation.agent.v1.RATLSRequest
	6, // 3: attestation.agent.v1.AttestationAgent.GetStatus:input_type -> attestation.agent.v1.StatusRequest
	1, // 4: attestation.agent.v1.AttestationAgent.LaunchContainer:output_type -> attestation.agent.v1.LaunchResponse
	3, // 5: attestation.agent.v1.AttestationAgent.GetQuote:output_type -> attestation.agent.v1.QuoteResponse
	5, // 6: attestation.agent.v1.AttestationAgent.GetRATLSCredentials:output_type -> attestation.agent.v1.RATLSResponse
	7, // 7: attestation.agent.v1.AttestationAgent.GetStatus:output_type -> attestation.agent.v1.StatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_agent_api_v1_agent_proto_init() }
func file_agent_api_v1_agent_proto_init() {
	if File_agent_api_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_api_v1_agent_proto_rawDesc), len(file_agent_api_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_api_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_api_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_api_v1_agent_proto = out.File
	file_agent_api_v1_agent_proto_goTypes = nil
	file_agent_api_v1_agent_proto_depIdxs = nil
}
