// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: agent/api/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttestationAgent_LaunchContainer_FullMethodName     = "/attestation.agent.v1.AttestationAgent/LaunchContainer"
	AttestationAgent_GetQuote_FullMethodName            = "/attestation.agent.v1.AttestationAgent/GetQuote"
	AttestationAgent_GetRATLSCredentials_FullMethodName = "/attestation.agent.v1.AttestationAgent/GetRATLSCredentials"
	AttestationAgent_GetStatus_FullMethodName           = "/attestation.agent.v1.AttestationAgent/GetStatus"
)

// AttestationAgentClient is the client API for AttestationAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttestationAgentClient interface {
	// Pull an OCI image, measure its manifest digest into RTMR[2], and start
	// the container. Returns the container ID and the digest that was extended.
	LaunchContainer(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error)
	// Generate a TDX quote with caller-supplied report data (64 bytes).
	GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error)
	// Generate an ephemeral TLS keypair with the TDX quote embedded in the
	// X.509 certificate (RA-TLS).
	GetRATLSCredentials(ctx context.Context, in *RATLSRequest, opts ...grpc.CallOption) (*RATLSResponse, error)
	// Health check — reports whether the agent is ready and whether TDX
	// hardware is available.
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type attestationAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestationAgentClient(cc grpc.ClientConnInterface) AttestationAgentClient {
	return &attestationAgentClient{cc}
}

func (c *attestationAgentClient) LaunchContainer(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchResponse)
	err := c.cc.Invoke(ctx, AttestationAgent_LaunchContainer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentClient) GetQuote(ctx context.Context, in *QuoteRequest, opts ...grpc.CallOption) (*QuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuoteResponse)
	err := c.cc.Invoke(ctx, AttestationAgent_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentClient) GetRATLSCredentials(ctx context.Context, in *RATLSRequest, opts ...grpc.CallOption) (*RATLSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RATLSResponse)
	err := c.cc.Invoke(ctx, AttestationAgent_GetRATLSCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AttestationAgent_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttestationAgentServer is the server API for AttestationAgent service.
// All implementations must embed UnimplementedAttestationAgentServer
// for forward compatibility.
type AttestationAgentServer interface {
	// Pull an OCI image, measure its manifest digest into RTMR[2], and start
	// the container. Returns the container ID and the digest that was extended.
	LaunchContainer(context.Context, *LaunchRequest) (*LaunchResponse, error)
	// Generate a TDX quote with caller-supplied report data (64 bytes).
	GetQuote(context.Context, *QuoteRequest) (*QuoteResponse, error)
	// Generate an ephemeral TLS keypair with the TDX quote embedded in the
	// X.509 certificate (RA-TLS).
	GetRATLSCredentials(context.Context, *RATLSRequest) (*RATLSResponse, error)
	// Health check — reports whether the agent is ready and whether TDX
	// hardware is available.
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedAttestationAgentServer()
}

// UnimplementedAttestationAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttestationAgentServer struct{}

func (UnimplementedAttestationAgentServer) LaunchContainer(context.Context, *LaunchRequest) (*LaunchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LaunchContainer not implemented")
}
func (UnimplementedAttestationAgentServer) GetQuote(context.Context, *QuoteRequest) (*QuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedAttestationAgentServer) GetRATLSCredentials(context.Context, *RATLSRequest) (*RATLSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRATLSCredentials not implemented")
}
func (UnimplementedAttestationAgentServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAttestationAgentServer) mustEmbedUnimplementedAttestationAgentServer() {}
func (UnimplementedAttestationAgentServer) testEmbeddedByValue()                          {}

// UnsafeAttestationAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestationAgentServer will
// result in compilation errors.
type UnsafeAttestationAgentServer interface {
	mustEmbedUnimplementedAttestationAgentServer()
}

func RegisterAttestationAgentServer(s grpc.ServiceRegistrar, srv AttestationAgentServer) {
	// If the following call panics, it indicates UnimplementedAttestationAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttestationAgent_ServiceDesc, srv)
}

func _AttestationAgent_LaunchContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServer).LaunchContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgent_LaunchContainer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServer).LaunchContainer(ctx, req.(*LaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgent_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgent_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServer).GetQuote(ctx, req.(*QuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgent_GetRATLSCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RATLSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServer).GetRATLSCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgent_GetRATLSCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServer).GetRATLSCredentials(ctx, req.(*RATLSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgent_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttestationAgent_ServiceDesc is the grpc.ServiceDesc for AttestationAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttestationAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attestation.agent.v1.AttestationAgent",
	HandlerType: (*AttestationAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchContainer",
			Handler:    _AttestationAgent_LaunchContainer_Handler,
		},
		{
			MethodName: "GetQuote",
			Handler:    _AttestationAgent_GetQuote_Handler,
		},
		{
			MethodName: "GetRATLSCredentials",
			Handler:    _AttestationAgent_GetRATLSCredentials_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AttestationAgent_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/api/v1/agent.proto",
}
